### ISSUE TITLE
CMS: Recipient Info (ktri vs kekri)

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/ipfs-encryption#18]
The current CMS `RecipientInfo` libp2p/js-libp2p-cms#1 uses the `ktri KeyTransRecipientInfo`, with the issuer's CN containing the key's id.  IPFS doesn't have distinguished names and it's basically a hack to send the key's ID.

```
   recipientInfos:
      d.ktri:
        version: <ABSENT>
        d.issuerAndSerialNumber:
          issuer: O=ipfs, OU=keystore, CN=QmWc1hrWTsh1sWkCKn5hd5AvMD4ZhRFwEtok2MhCAzpuvx
          serialNumber: 1
        keyEncryptionAlgorithm:
          algorithm: rsaEncryption (1.2.840.113549.1.1.1)
          parameter: NULL
        encryptedKey: ...
```

The ` kekri` [KEKRecipientInfo](https://tools.ietf.org/html/rfc5652#section-6.2.3) is more suited to IPFS; it uses a key ID instead of a distinguished name.  However, the spec does state that

> Recipient information using previously distributed **symmetric** keys
